### ISSUE TITLE
export not happening

### ISSUE THREAD

**Issue by quin-q** [realityfabric/Tumblr-Batch-Block#6]
basically, clicking the export button has no effect at the moment - at least for me

**Comment by realityfabric** [comment]
Are you clicking the export button while on your settings page where you would normally access the block list? It won't work on any other page.

Things that should happen when you click the export button:

- The list of blocked users should open
- The list of blocked users should begin to expand (the extension opens the list entirely by clicking the "Show More" button until there are no more blocked blogs)
- Once the list has expanded fully, a textbox should appear at the top of the page, upper right-hand corner. This box should be filled with all the blogs which are in your block list.

Does any of this happen for you?

**Comment by donkeyfly69** [comment]
I'm having the same issue using Version 75.0.3770.142 of chrome. I tried the suggestions above.

**Comment by realityfabric** [comment]
Does anything at all happen when you try? Or does nothing happen at all?

**Comment by donkeyfly69** [comment]
Nothing happens at all. Tried restarting chrome and my laptop.

**Comment by realityfabric** [comment]
Which version of TBB are you using?
And and you open the dev console (F12) and post what it says when you click the button?

Also, try running it with no other extensions, it could be a conflict with something else.

**Comment by donkeyfly69** [comment]
I wasn't able to see what it said when I clicked the button with the dev console. But closing all the other extensions and restarting it, it was able to work! Thank you!

**Comment by donkeyfly69** [comment]
Also it was the latest tbb.

**Comment by realityfabric** [comment]
Glad that worked for you!
